server:
  port: 8040

spring:
  application:
    name: simple-gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: '*'
  routes:
    simpleConsumerUser: /user/**
logging:
  level:
    com.netflix: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
